# Generated by Django 5.1.3 on 2024-12-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_itemestoque_cor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itenspedido',
            old_name='item_estoques',
            new_name='item_estoque',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
